# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d801a24d6de49fd4e09d0153e1e593598f51ae677fd2f641ca77fcfb1b2baa6b6f38979f144a0fc6394d1eaeda689560bb02d2f4c2c5a0367e1bb947aee1dbf9

test:
  secret_key_base: 499230505dee4a80c6e5712521f9ea5b6d8daa49c95661830a16466469d45f99fe3216fbe3046eee818b5cf7fca2440ac658da4f9bd988b801aa576c0ff08156

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
